spring.application.name=JESP_Core

server.port=5001

spring.datasource.url=jdbc:sqlite:${JESP_DB_PATH:jesp_data.db}
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.hikari.maximum-pool-size=1

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

jesp.rules-file=${JESP_RULES_FILE:rules.conf}
jesp.ws-port=${JESP_WS_PORT:5000}