services:
  core:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jesp-core
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      JESP_DB_PATH: /app/data/jesp_data.db
      JESP_RULES_FILE: /app/data/rules.conf
      TZ: Europe/Madrid
    volumes:
      - jesp-data:/app/data
    restart: unless-stopped

volumes:
  jesp-data: